# Generated by Django 6.0.1 on 2026-01-28 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Configuração do Site', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='site_title',
            new_name='site_name',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='items_per_page',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Frete Grátis acima de (R$)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
