# Generated by Django 6.0.1 on 2026-01-27 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_appointment'),
        ('Clients', '0002_remove_client_created_at_and_more'),
        ('Orders', '0003_remove_coupon_discount_percentage_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='discount_percent',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Clients.client'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Assets.product'),
        ),
    ]
