# Generated by Django 6.0.1 on 2026-01-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Nota Fiscal/Recibo')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago?')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='Orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('method', models.CharField(choices=[('PIX', 'Pix'), ('CC', 'Cartão Crédito'), ('CD', 'Cartão Débito'), ('CASH', 'Dinheiro')], max_length=10, verbose_name='Método')),
                ('transaction_id', models.CharField(blank=True, help_text='ID do Pix ou código da maquininha', max_length=100, verbose_name='ID da Transação')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Estornado')),
                ('reason', models.TextField(verbose_name='Motivo do Estorno')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='Billing.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
