# Generated by Django 6.0.1 on 2026-02-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Checkout Stripe'),
        ),
    ]
