# Generated by Django 6.0.1 on 2026-01-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='EletricBike', max_length=100, verbose_name='Nome do Site')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo Manutenção')),
                ('contact_email', models.EmailField(default='contato@eletricbike.com', max_length=254, verbose_name='Email de Contato')),
                ('items_per_page', models.IntegerField(default=12, verbose_name='Itens por página')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
