# Generated by Django 6.0.1 on 2026-01-19 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(default='Praia Grande', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(default='SP', max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=9, verbose_name='CEP')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('role', models.CharField(max_length=50, verbose_name='Vínculo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Clients.client')),
            ],
        ),
    ]
