# Generated by Django 6.0.1 on 2026-01-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Usado na URL (ex: /pecas/eletrica)', unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Classe do ícone (ex: fas fa-bolt)', max_length=50)),
                ('is_service', models.BooleanField(default=False, help_text='Categoria exclusiva para mão de obra?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='Assets.category')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Código de barras ou interno', max_length=50, null=True, unique=True, verbose_name='SKU/Código')),
                ('product_type', models.CharField(choices=[('BIKE', 'Bicicleta Elétrica'), ('COMPONENT', 'Peça/Componente'), ('ACCESSORY', 'Acessório'), ('SERVICE', 'Serviço/Mão de Obra'), ('KIT', 'Kit de Conversão')], default='COMPONENT', max_length=20, verbose_name='Tipo')),
                ('ownership', models.CharField(choices=[('SHOP', 'Estoque da Loja (Venda)'), ('CUSTOMER', 'Pertence ao Cliente (Manutenção)')], default='SHOP', max_length=10, verbose_name='Propriedade')),
                ('condition', models.CharField(choices=[('NEW', 'Novo'), ('USED', 'Seminovo/Usado'), ('OPEN_BOX', 'Open Box'), ('REFURBISHED', 'Recondicionado')], default='NEW', max_length=20, verbose_name='Condição')),
                ('description', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('short_description', models.CharField(blank=True, help_text='Para exibição em cards', max_length=200, verbose_name='Resumo')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('min_stock_alert', models.IntegerField(default=2, verbose_name='Alerta Mínimo')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='Imagem Capa')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Assets.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer_complaint', models.TextField(verbose_name='Reclamação/Problema')),
                ('technical_report', models.TextField(blank=True, verbose_name='Laudo Técnico')),
                ('mechanic_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Orçamento'), ('APPROVED', 'Aprovado'), ('IN_PROGRESS', 'Em Execução'), ('WAITING_PARTS', 'Aguardando Peças'), ('READY', 'Pronto para Retirada'), ('DELIVERED', 'Entregue/Finalizado')], default='PENDING', max_length=20)),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Data Entrada')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Previsão Entrega')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Mão de Obra')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Peças')),
                ('product_item', models.ForeignKey(limit_choices_to={'ownership': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='Assets.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Assets.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.DecimalField(blank=True, decimal_places=1, help_text='Ex: 36, 48, 52, 60, 72', max_digits=5, null=True, verbose_name='Voltagem (V)')),
                ('amperage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Amperagem/Capacidade (Ah)')),
                ('wattage', models.IntegerField(blank=True, help_text='Potência nominal do motor ou pico', null=True, verbose_name='Potência (W)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='Ex: 10x5x2 cm ou Aro 29', max_length=100, verbose_name='Dimensões')),
                ('material', models.CharField(blank=True, help_text='Ex: Alumínio 6061, Nylon, Li-Ion', max_length=50, verbose_name='Material')),
                ('max_speed', models.IntegerField(blank=True, null=True, verbose_name='Velocidade Máx (km/h)')),
                ('range_estimate', models.CharField(blank=True, max_length=50, verbose_name='Autonomia Estimada')),
                ('charging_time', models.CharField(blank=True, max_length=50, verbose_name='Tempo de Recarga')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='Assets.product')),
            ],
            options={
                'verbose_name': 'Especificação Técnica',
            },
        ),
    ]
