# Generated by Django 6.0.1 on 2026-01-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
        ('Clients', '0002_remove_client_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(verbose_name='Data Agendada')),
                ('time', models.CharField(choices=[('09:00', '09:00 - 10:00'), ('10:00', '10:00 - 11:00'), ('11:00', '11:00 - 12:00'), ('14:00', '14:00 - 15:00'), ('15:00', '15:00 - 16:00'), ('16:00', '16:00 - 17:00')], max_length=10, verbose_name='Horário')),
                ('service_type', models.CharField(default='Revisão Geral', max_length=100, verbose_name='Tipo de Serviço')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente de Aprovação'), ('CONFIRMED', 'Confirmado'), ('CANCELED', 'Cancelado'), ('COMPLETED', 'Realizado')], default='PENDING', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Clients.client')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
